name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Frontend Docker image
      run: cd src/frontend && docker build . --file Dockerfile --tag annonce-ventes-frontend:$(date +%s)
    - name: Build the Backend Docker image
      run: cd src/backend && docker build . --file Dockerfile --tag annonce-ventes-backend:$(date +%s)
